name: Close Stale Issues and PRs
on:
  schedule:
    # Runs every day at 1:30 AM
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: "このIssueは古くなっています"
          stale-pr-message: "このPull Requestは古くなっています"
          close-issue-message: "このIssueは古いので閉じられました"
          close-pr-message: "このPull Requestは古いので閉じられました"
          days-before-stale: 60
          days-before-close: 10
          stale-issue-label: "stale"
